---
- name: "Setup | Firewall | Get firewall configuration for server"
  community.hrobot.firewall_info:
    hetzner_user: "{{ hetzner_server_setup_api_username }}"
    hetzner_password: "{{ hetzner_server_setup_api_password }}"
    server_ip: "{{ hetzner_server_setup_ip }}"
    filter_ipv6: true
    allowlist_hos: true
    rules: "{{ hetzner_server_setup_firewall_rules | d(omit) }}"
  register: "_hetzner_server_setup_firewall_result"
  when:
    - "hetzner_server_setup_ip is defined"
    - "hetzner_server_setup_firewall_rules is defined"

- name: "Setup | Firewall | Show firewall configuration"
  ansible.builtin.debug:
    msg: "{{ _hetzner_server_setup_firewall_result }}"
  when: "_hetzner_server_setup_firewall_result is defined"

...
