---
- name: "Setup | Firewall | Configure firewall configuration for server"
  community.hrobot.firewall:
    hetzner_user: "{{ hetzner_server_setup_api_username }}"
    hetzner_password: "{{ hetzner_server_setup_api_password }}"
    server_ip: "{{ hetzner_server_setup_ip }}"
    state: "present"
    filter_ipv6: true
    allowlist_hos: true
    rules:
      input: "{{ hetzner_server_setup_firewall_inbound_rules | d(omit) }}"
      output: ""

  register: "_hetzner_server_setup_firewall_result"
  when:
    - "hetzner_server_setup_ip is defined"
    # - "hetzner_server_setup_firewall_rules is defined"

- name: "Setup | Firewall | Show firewall configuration"
  ansible.builtin.debug:
    msg: "{{ _hetzner_server_setup_firewall_result }}"
  when: "_hetzner_server_setup_firewall_result is defined"

...
