---
checkmk_server_setup_file: "check-mk-{{ checkmk_server_edition_mapping[checkmk_server_edition] }}-{{ checkmk_server_version }}-el{{ ansible_facts.distribution_major_version }}-38.x86_64.rpm" # noqa yaml[line-length]

_checkmk_server_epel_version:
  default: "{{ ansible_facts.distribution_major_version }}"

checkmk_server_epel_version: "{{ _checkmk_server_epel_version[ansible_facts.distribution ~ '-' ~ ansible_facts.distribution_major_version] | default(
  _checkmk_server_epel_version['default'] ) }}"

checkmk_server_epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ checkmk_server_epel_version }}.noarch.rpm"

checkmk_server_epel_next_url: "https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-{{ checkmk_server_epel_version }}.noarch.rpm"

checkmk_server_epel_gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ checkmk_server_epel_version }}"

checkmk_server_epel_dl_fedora: true

_checkmk_server_prerequisites:
  CentOS-7:
    - dnf-plugins-core
    - firewalld
  CentOS-8:
    - dnf-plugins-core
    - firewalld
  RedHat-7:
    - libsemanage-python
    - firewalld
    - yum-plugins-core
    - jq
  RedHat-8:
    - python3-libsemanage
    - firewalld
    - dnf-plugins-core
    - jq
  #RedHat-9:
  #  - python3-libsemanage
  #  - firewalld
  #  - dnf-plugins-core

checkmk_server_prerequisites: "{{ _checkmk_server_prerequisites[ansible_facts.distribution ~ '-' ~ ansible_facts.distribution_major_version] | default(
  _checkmk_server_prerequisites[ansible_facts.distribution]) }}"

checkmk_server_ports:
  - 80/tcp
  - 8000/tcp
  - 443/tcp

...
