---
- name: "SSHKeys | display message"
  ansible.builtin.debug:
    msg: "Setup role {{ hetzner_server_role_name }} for {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"

- name: "SSHKeys | Retrieve first public key fingerprint"
  ansible.builtin.uri:
    url: "{{ hetzner_server_api_url }}/key"
    return_content: yes
    method: GET
    user: "{{ hetzner_server_api_username }}"
    password: "{{ hetzner_server_api_password }}"
    force_basic_auth: yes
    status_code: 200
  register: _hetzner_server_key
  delegate_to: localhost

- name: "SsHkeys | Set authorized_key fact"
  ansible.builtin.set_fact:
    hetzner_server_authorized_key: "{{ _hetzner_server_key.json[0].key.fingerprint }}"

- name: "SSHKeys | Display authorized_key fact"
  ansible.builtin.debug:
    var: hetzner_server_authorized_key

...
