---
galaxy_info:
  author: Marc Ouwerkerk.
  role_name: hetzner_server
  description: Provision Hetzner Dedicated server with rescue
  license: Apache-2.0
  min_ansible_version: "2.10"
  standalone: true

  platforms:
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - mto79
    - hetzner
    - hetzner_robot
    - server

dependencies: []

...
