---
- name: "Assert | test if hetzner_rescue_role_name is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_role_name is defined
      - hetzner_rescue_role_name is string
      - hetzner_rescue_role_name in ["hetzner_rescue"]
    quiet: true

- name: "Assert | test if hetzner_rescue_api_url is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_api_url is defined
      - hetzner_rescue_api_url is string
    quiet: true

- name: "Assert | test if hetzner_rescue_api_username is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_api_username is defined
      - hetzner_rescue_api_username is string
    quiet: true

- name: "Assert | test if hetzner_rescue_api_password is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_api_password is defined
      - hetzner_rescue_api_password is encrypted
    quiet: true

- name: "Assert | test if hetzner_rescue_hostname is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_hostname is defined
      - hetzner_rescue_hostname is string
    quiet: true

- name: "Assert | test if hetzner_rescue_ip is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_ip is defined
      - hetzner_rescue_ip is string
    quiet: true

- name: "Assert | test if hetzner_rescue_disk1 is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_disk1 is defined
      - hetzner_rescue_disk1 is string
      - hetzner_rescue_disk1 in ["sda"]
    quiet: true

- name: "Assert | test if hetzner_rescue_disk2 is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_disk2 is defined
      - hetzner_rescue_disk2 is string
      - hetzner_rescue_disk2 in ["sdb"]
    quiet: true

- name: "Assert | test if hetzner_rescue_image is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_rescue_image is defined
      - hetzner_rescue_image is string
    quiet: true

- name: "Assert | test if hetzner_rescue_image_ignore_errors is set correctly."
  ansible.builtin.assert:
    quiet: true
    that:
      - hetzner_rescue_image_ignore_errors is defined
      - hetzner_rescue_image_ignore_errors  is boolean

...
