---
- name: "Assert | Test if __role_name is set correctly"
  ansible.builtin.assert:
    that:
      - __role_name is defined
      - __role_name is string
      - __role_name in ["hetzner_server"]
    quiet: true

- name: "Assert | Definitions for Setup"
  when: "'setup' in __role_action"
  block:

    - name: "Assert | Test if hetzner_server_setup_api_url is set correctly"
      ansible.builtin.assert:
        that:
          - "hetzner_server_setup_api_url is defined"
          - "hetzner_server_setup_api_url is string"
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_api_username is set correctly"
      ansible.builtin.assert:
        that:
          - "hetzner_server_setup_api_username is defined"
          - "hetzner_server_setup_api_username is string"
          - "hetzner_server_setup_api_username | length > 0"
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_api_password is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_api_password is defined
          - hetzner_server_setup_api_password is string
          - hetzner_server_setup_api_password | length > 0
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_disk1 is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_disk1 is defined
          - hetzner_server_setup_disk1 is string
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_disk2 is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_disk2 is defined
          - hetzner_server_setup_disk2 is string
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_hostname is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_hostname is defined
          - hetzner_server_setup_hostname is string
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_image is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_image is defined
          - hetzner_server_setup_image is string
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_image_source is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_image_source is defined
          - hetzner_server_setup_image_source is string
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_image_ignore_errors is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_image_ignore_errors is defined
          - hetzner_server_setup_image_ignore_errors is boolean
        quiet: true

    - name: "Assert | Test if hetzner_server_setup_size_of_libvirt_images is set correctly"
      ansible.builtin.assert:
        that:
          - hetzner_server_setup_size_of_libvirt_images is defined
          - hetzner_server_setup_size_of_libvirt_images is string
          - hetzner_server_setup_size_of_libvirt_images in ["all", "small", "medium", "large"]
        quiet: true

...
