---
- name: "Assert | test if hetzner_server_role_name is set correctly"
  ansible.builtin.assert:
    that:
      - hetzner_server_role_name is defined
      - hetzner_server_role_name is string
      - hetzner_server_role_name in ["hetzner_server"]
    quiet: true

...
