---
- name: "Setup | Manage SSH keys"
  ansible.builtin.include_tasks: 
    file: "sshkeys.yml"

- name: "Setup | Manage Servers"
  ansible.builtin.include_tasks: 
    file: "servers.yml"


#- name: "Setup | Display infor selected server"
#  ansible.builtin.debug:
#    msg: "Selected server {{ hetzner_server_number }} with IP {{ hetzner_server_ip }} and key"
#  delegate_to: localhost

#- name: "Setup | Retrieve current setup of {{ hetzner_server_ip }}"
#  ansible.builtin.gather_facts:
#  register: _hetzner_server_host_facts
#  delegate_to: "{{ hetzner_server_ip }}"

#- name: "Setup | Check Boot image and hetzner_force_provisioning"
#  ansible.builtin.set_fact:
#    _hetzner_server_needs_reprovision: true
#  when:
#    - _hetzner_server_host_facts.ansible_facts.ansible_cmdline.BOOT_IMAGE is match("rescue") or (hetzner_server_force_provisioning is defined and hetzner_server_force_provisioning )
#  delegate_to: localhost

#- name: "Setup | Check rescue mode"
#  ansible.builtin.uri:
#    url: "{{ hetzner_server_api_url }}/boot/{{ hetzner_server_number }}/rescue"
#    method: GET
#    user: "{{ hetzner_server_api_username }}"
#    password: "{{ hetzner_server_api_password }}"
#    force_basic_auth: yes
#    status_code: 200
#  register: _hetzner_server_rescue
#  delegate_to: localhost

#- name: "Setup | Display rescue mode"
#  ansible.builtin.debug:
#    msg: "Rescue mode is {{ _hetzner_server_rescue.json.rescue.active }}"
#  delegate_to: localhost


...
