---
- name: "Setup | Manage SSH keys"
  ansible.builtin.include_tasks:
    file: "sshkeys.yml"

- name: "Setup | Manage Servers"
  ansible.builtin.include_tasks:
    file: "servers.yml"

- name: "Setup | Display infor selected server"
  ansible.builtin.debug:
    msg: "Selected server {{ hetzner_server_number }} with IP {{ hetzner_server_ip }} and authorized_key {{ hetzner_server_authorized_key }}"
  failed_when: hetzner_server_number is not defined or hetzner_server_number == "" or
      hetzner_server_ip is not defined or hetzner_server_ip == "" or
      hetzner_server_authorized_key is not defined or hetzner_server_authorized_key == ""
  delegate_to: localhost

- name: "Setup | Rescue Server"
  ansible.builtin.include_tasks:
    file: "rescue.yml"

- name: "Setup | Wait 600 seconds for port 22 to become open"
  ansible.builtin.wait_for:
    port: 22
    host: '{{ hetzner_server_ip }}'
    delay: 10
    timeout: 600
  connection: local

- name: "Setup | Refresh information after re-install of {{ hetzner_server_ip }}"
  ansible.builtin.gather_facts:
  register: _hetzner_server_host_facts
  delegate_to: "{{ hetzner_server_ip }}"

...
